### ISSUE TITLE
Galactic release

### ISSUE THREAD

**Issue by Timple** [oKermorgant/simple_launch#2]
I noticed this package has been released (bloomed) for foxy, but not yet galactic.

Would that be possible? Thanks in advance :slightly_smiling_face:

**Comment by oKermorgant** [comment]
Hi, 
Sure, I do not have Galactic installed but I guess the package can be released in Galactic and Rolling. 
Have you tried it with the source in Galactic?

I'll do a release this week.

**Comment by Timple** [comment]
Yes, verified to be working. Thankyou

**Comment by oKermorgant** [comment]
All set! https://github.com/ros/rosdistro/pull/31103

Thanks for using this package, updates will become rare as the important features seem to have converged.
